/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ClientOptions {
  proxy?: string
  allowRedirect?: boolean
  headerOrder?: Array<string>
  splitCookies?: boolean
  debug?: boolean
  timeout?: number
}

export declare class QueryEngine {}
export type JsQueryEngine = QueryEngine

export declare class TlsClient {
  constructor(opt: ClientOptions)
  post(
    url: string,
    data?: string | undefined | null,
    headers?: Record<string, string> | undefined | null,
  ): Promise<HttpResponse>
  get(url: string, headers?: Record<string, string> | undefined | null): Promise<HttpResponse>
  clearCookies(): void
  setCookies(cookies: Record<string, string>, url: string): void
  getCookies(): Record<string, string>
}

export interface HttpResponse {
  status: number
  errorMsg: string
  statusCode: number
  body: string
  content: string
  headers: Record<string, string>
  url: string
}

export declare function newOptions(
  proxy?: string | undefined | null,
  allowRedirect?: boolean | undefined | null,
  headerOrder?: Array<string> | undefined | null,
  splitCookies?: boolean | undefined | null,
  debug?: boolean | undefined | null,
  timeout?: number | undefined | null,
): ClientOptions
